from .home import HomeView
from .signup import SignUpView
from .login import LogInView
from .cliente import ClientesView
from .perfil import PerfilView
from .coordinador import CoordinadoresView
from .sede import SedesView
from .proveedores import ProveedoresView
from .evento import EventosView
from .dashboard import DashBoard